import { useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { Sparkles } from "lucide-react";
import { api } from "../api/client.js";
import AppShell from "../components/AppShell.jsx";

// Requirements input -> AI recommendation -> review/edit -> apply.
// This is the "Business Requirements -> Module Recommendations" flow
// from the project concept, with the AI output always shown for review
// before anything is saved (never auto-applied blindly).
export default function SetupPage() {
  const { businessId } = useParams();
  const navigate = useNavigate();
  const [description, setDescription] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [config, setConfig] = useState(null);
  const [source, setSource] = useState(null);
  const [applying, setApplying] = useState(false);

  async function handleGenerate(e) {
    e.preventDefault();
    setError("");
    setLoading(true);
    try {
      const result = await api.getAiRecommendation(businessId, description);
      setConfig(result.config);
      setSource(result.source);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }

  function removeModule(idx) {
    setConfig((c) => ({ modules: c.modules.filter((_, i) => i !== idx) }));
  }

  function removeField(modIdx, fieldIdx) {
    setConfig((c) => {
      const modules = [...c.modules];
      modules[modIdx] = {
        ...modules[modIdx],
        fields: modules[modIdx].fields.filter((_, i) => i !== fieldIdx),
      };
      return { modules };
    });
  }

  async function handleApply() {
    setApplying(true);
    setError("");
    try {
      await api.applyConfig(businessId, config.modules);
      navigate(`/business/${businessId}/dashboard`);
    } catch (err) {
      setError(err.message);
      setApplying(false);
    }
  }

  return (
    <AppShell>
    <div className="px-8 py-10 max-w-2xl">
      <h1 className="font-display text-2xl text-ink mb-1">Describe your business</h1>
      <p className="text-sm text-muted mb-6">
        We'll recommend modules and fields. You can edit everything before it's created.
      </p>

      <form onSubmit={handleGenerate} className="space-y-3 mb-8">
        <textarea
          rows={3}
          required
          placeholder="e.g. I run a clothing business and need to manage inventory, suppliers, customers, sales and expenses"
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          className="w-full px-3 py-2 border border-line rounded text-sm bg-panel focus:outline-none focus:ring-2 focus:ring-accent/40"
        />
        <button
          type="submit"
          disabled={loading}
          className="flex items-center gap-2 px-4 py-2 bg-accent text-white rounded text-sm font-medium disabled:opacity-50"
        >
          <Sparkles size={15} /> {loading ? "Generating..." : "Get recommendations"}
        </button>
        {error && <p className="text-sm text-red-600">{error}</p>}
      </form>

      {config && (
        <div className="space-y-5">
          <div className="flex items-center justify-between">
            <h2 className="text-sm font-medium text-ink">
              Recommended modules{" "}
              <span className="text-xs text-muted font-normal">
                ({source === "ai" ? "generated by AI" : "offline template — configure ANTHROPIC_API_KEY for live AI"})
              </span>
            </h2>
          </div>

          {config.modules.map((mod, mi) => (
            <div key={mi} className="bg-panel border border-line rounded p-4">
              <div className="flex items-center justify-between mb-2">
                <p className="text-sm font-semibold text-ink">{mod.name}</p>
                <button onClick={() => removeModule(mi)} className="text-xs text-muted hover:text-red-600">
                  Remove module
                </button>
              </div>
              <div className="space-y-1">
                {mod.fields.map((f, fi) => (
                  <div key={fi} className="flex items-center justify-between text-sm text-muted py-1 border-t border-line first:border-t-0">
                    <span>
                      {f.label} <span className="text-xs">({f.type}{f.required ? ", required" : ""})</span>
                    </span>
                    <button onClick={() => removeField(mi, fi)} className="text-xs hover:text-red-600">
                      Remove
                    </button>
                  </div>
                ))}
              </div>
            </div>
          ))}

          <button
            onClick={handleApply}
            disabled={applying || config.modules.length === 0}
            className="px-5 py-2.5 bg-accent text-white rounded text-sm font-medium disabled:opacity-50"
          >
            {applying ? "Creating..." : "Create these modules"}
          </button>
        </div>
      )}
    </div>
    </AppShell>
  );
}
